name: Spence-s
permalink: /blog/:year/:month/:day/:title
exclude: ['node_modules', 'sass', 'Gemfile', 'gulpfile.js', '*.lock', '*.json']
collections:
  projects:
    output: true
future: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
