name: Spence-s
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: ['node_modules', 'sass', 'Gemfile', 'gulpfile.js', '*.lock', '*.json']
collections:
  projects:
future: true
highlighter: rouge
